### ISSUE TITLE
please mark the license in maubot.yaml on all of your plugins

### ISSUE THREAD

**Issue by chayleaf** [williamkray/maubot-createroom#1]
I'm the author of [maubot.nix](https://github.com/chayleaf/maubot.nix), which is used for configuring maubot on NixOS. Having the plugins list all of their dependencies and licenses in maubot.yaml is very convenient for packaging. Your plugins are currently marked as proprietary, because they don't have the license set in maubot.yaml. See [an example](https://github.com/maubot/disruptor/blob/master/maubot.yaml) of an official maubot.yaml with a license set.

I'm working on using the new plugin repo so I won't have that problem anymore, but this is still a good thing to do.

**Comment by williamkray** [comment]
Thank you for pointing this out, I added the licenses hastily and forgot to include them in the manifest file. I'll update them today.

**Comment by williamkray** [comment]
fixed for this repo and my other plugins as well.
